/**
 * Side-effect imports — registers all DUI components.
 * Also re-exports all classes for programmatic use.
 */

import "./accordion/index.ts";
import "./alert-dialog/index.ts";
import "./avatar/index.ts";
import "./badge/index.ts";
import "./breadcrumb/index.ts";
import "./button/index.ts";
import "./calendar/index.ts";
import "./card/index.ts";
import "./card-grid/index.ts";
import "./checkbox/index.ts";
import "./collapsible/index.ts";
import "./combobox/index.ts";
import "./command/index.ts";
import "./data-table/index.ts";
import "./dialog/index.ts";
import "./dropzone/index.ts";
import "./field/index.ts";
import "./fieldset/index.ts";
import "./icon/index.ts";
import "./input/index.ts";
import "./menu/index.ts";
import "./menubar/index.ts";
import "./number-field/index.ts";
import "./popover/index.ts";
import "./portal/index.ts";
import "./preview-card/index.ts";
import "./progress/index.ts";
import "./radio/index.ts";
import "./scroll-area/index.ts";
import "./select/index.ts";
import "./separator/index.ts";
import "./sidebar/index.ts";
import "./slider/index.ts";
import "./spinner/index.ts";
import "./split-button/index.ts";
import "./splitter/index.ts";
import "./stepper/index.ts";
import "./switch/index.ts";
import "./tabs/index.ts";
import "./textarea/index.ts";
import "./toast/index.ts";
import "./toggle/index.ts";
import "./toolbar/index.ts";
import "./tooltip/index.ts";
import "./tree/index.ts";
import "./trunc/index.ts";

export { DuiAccordion } from "./accordion/index.ts";
export { DuiAccordionItem } from "./accordion/index.ts";
export { DuiAlertDialog } from "./alert-dialog/index.ts";
export { DuiAlertDialogClose } from "./alert-dialog/index.ts";
export { DuiAlertDialogPopup } from "./alert-dialog/index.ts";
export { DuiAlertDialogTrigger } from "./alert-dialog/index.ts";
export { DuiAvatar } from "./avatar/index.ts";
export { DuiBadge } from "./badge/index.ts";
export { DuiBreadcrumb } from "./breadcrumb/index.ts";
export { DuiBreadcrumbEllipsis } from "./breadcrumb/index.ts";
export { DuiBreadcrumbItem } from "./breadcrumb/index.ts";
export { DuiBreadcrumbLink } from "./breadcrumb/index.ts";
export { DuiBreadcrumbPage } from "./breadcrumb/index.ts";
export { DuiBreadcrumbSeparator } from "./breadcrumb/index.ts";
export { DuiButton } from "./button/index.ts";
export { DuiCalendar } from "./calendar/index.ts";
export { DuiCard } from "./card/index.ts";
export { DuiCardGrid } from "./card-grid/index.ts";
export { DuiCheckbox } from "./checkbox/index.ts";
export { DuiCheckboxGroup } from "./checkbox/index.ts";
export { DuiCollapsible } from "./collapsible/index.ts";
export { DuiCombobox } from "./combobox/index.ts";
export { DuiCommand } from "./command/index.ts";
export { DuiCommandEmpty } from "./command/index.ts";
export { DuiCommandGroup } from "./command/index.ts";
export { DuiCommandInput } from "./command/index.ts";
export { DuiCommandItem } from "./command/index.ts";
export { DuiCommandList } from "./command/index.ts";
export { DuiCommandSeparator } from "./command/index.ts";
export { DuiCommandShortcut } from "./command/index.ts";
export { DuiDataTable } from "./data-table/index.ts";
export { DuiDialog } from "./dialog/index.ts";
export { DuiDialogClose } from "./dialog/index.ts";
export { DuiDialogPopup } from "./dialog/index.ts";
export { DuiDialogTrigger } from "./dialog/index.ts";
export { DuiDropzone } from "./dropzone/index.ts";
export { DuiField } from "./field/index.ts";
export { DuiFieldset } from "./fieldset/index.ts";
export { DuiIcon } from "./icon/index.ts";
export { DuiInput } from "./input/index.ts";
export { DuiMenu } from "./menu/index.ts";
export { DuiMenuItem } from "./menu/index.ts";
export { DuiMenubar } from "./menubar/index.ts";
export { DuiNumberField } from "./number-field/index.ts";
export { DuiPopover } from "./popover/index.ts";
export { DuiPopoverClose } from "./popover/index.ts";
export { DuiPopoverPopup } from "./popover/index.ts";
export { DuiPopoverTrigger } from "./popover/index.ts";
export { DuiPortal } from "./portal/index.ts";
export { DuiPreviewCard } from "./preview-card/index.ts";
export { DuiPreviewCardPopup } from "./preview-card/index.ts";
export { DuiPreviewCardTrigger } from "./preview-card/index.ts";
export { DuiProgress } from "./progress/index.ts";
export { DuiRadio } from "./radio/index.ts";
export { DuiRadioGroup } from "./radio/index.ts";
export { DuiScrollArea } from "./scroll-area/index.ts";
export { DuiSelect } from "./select/index.ts";
export { DuiSeparator } from "./separator/index.ts";
export { DuiSidebar } from "./sidebar/index.ts";
export { DuiSidebarContent } from "./sidebar/index.ts";
export { DuiSidebarFooter } from "./sidebar/index.ts";
export { DuiSidebarGroup } from "./sidebar/index.ts";
export { DuiSidebarGroupLabel } from "./sidebar/index.ts";
export { DuiSidebarHeader } from "./sidebar/index.ts";
export { DuiSidebarInset } from "./sidebar/index.ts";
export { DuiSidebarMenu } from "./sidebar/index.ts";
export { DuiSidebarMenuButton } from "./sidebar/index.ts";
export { DuiSidebarMenuItem } from "./sidebar/index.ts";
export { DuiSidebarProvider } from "./sidebar/index.ts";
export { DuiSidebarSeparator } from "./sidebar/index.ts";
export { DuiSidebarTrigger } from "./sidebar/index.ts";
export { DuiSlider } from "./slider/index.ts";
export { DuiSpinner } from "./spinner/index.ts";
export { DuiSplitButton } from "./split-button/index.ts";
export { DuiSplitter } from "./splitter/index.ts";
export { DuiSplitterHandle } from "./splitter/index.ts";
export { DuiSplitterPanel } from "./splitter/index.ts";
export { DuiStepper } from "./stepper/index.ts";
export { DuiSwitch } from "./switch/index.ts";
export { DuiTab } from "./tabs/index.ts";
export { DuiTabs } from "./tabs/index.ts";
export { DuiTabsIndicator } from "./tabs/index.ts";
export { DuiTabsList } from "./tabs/index.ts";
export { DuiTabsPanel } from "./tabs/index.ts";
export { DuiTextarea } from "./textarea/index.ts";
export {
  DuiToast,
  DuiToastAction,
  DuiToastClose,
  DuiToastRegion,
  toast,
} from "./toast/index.ts";
export { DuiToggle } from "./toggle/index.ts";
export { DuiToggleGroup } from "./toggle/index.ts";
export { DuiToolbar } from "./toolbar/index.ts";
export { DuiTooltip } from "./tooltip/index.ts";
export { DuiTooltipPopup } from "./tooltip/index.ts";
export { DuiTooltipTrigger } from "./tooltip/index.ts";
export { DuiTree } from "./tree/index.ts";
export { DuiTreeItem } from "./tree/index.ts";
export { DuiTrunc } from "./trunc/index.ts";

export type { AccordionContext } from "@dui/primitives/accordion";
export type { AlertDialogOpenChangeDetail } from "@dui/primitives/alert-dialog";
export type { AlertDialogContext } from "@dui/primitives/alert-dialog";
export type { ImageStatus } from "@dui/primitives/avatar";
export type { CheckboxGroupContext } from "@dui/primitives/checkbox";
export type { SelectOption, ComboboxValueChangeDetail, ComboboxValuesChangeDetail } from "@dui/primitives/combobox";
export type { CommandContext, CommandItemEntry } from "@dui/primitives/command";
export type { ColumnDef, SortDirection, SortState, PageState } from "@dui/primitives/data-table";
export type { DialogOpenChangeDetail } from "@dui/primitives/dialog";
export type { DialogContext } from "@dui/primitives/dialog";
export type { DropzoneErrorCode, DropzoneRejectionCode, FileRejectionError, RejectedFile, DropzoneDropDetail, DropzoneAcceptedDetail, DropzoneRejectedDetail, DropzoneErrorDetail } from "@dui/primitives/dropzone";
export type { MenubarContext } from "@dui/primitives/menubar";
export type { PopoverOpenChangeDetail } from "@dui/primitives/popover";
export type { PopoverContext, PopoverSide } from "@dui/primitives/popover";
export type { QueryRoot } from "@dui/primitives/portal";
export type { PreviewCardOpenChangeDetail } from "@dui/primitives/preview-card";
export type { PreviewCardContext, PreviewCardSide } from "@dui/primitives/preview-card";
export type { RadioGroupContext } from "@dui/primitives/radio";
export type { SidebarOpenChangeDetail } from "@dui/primitives/sidebar";
export type { SidebarContext } from "@dui/primitives/sidebar";
export type { SplitterContext, SplitterHandleAria, SplitterHandleMeta, SplitterPanelMeta } from "@dui/primitives/splitter";
export type { TabsContext } from "@dui/primitives/tabs";
export type { TextareaResize } from "@dui/primitives/textarea";
export type { ToggleGroupContext } from "@dui/primitives/toggle";
export type { TooltipOpenChangeDetail } from "@dui/primitives/tooltip";
export type { TooltipContext, TooltipSide } from "@dui/primitives/tooltip";
export type { SelectionMode, TreeContext } from "@dui/primitives/tree";
