/**
 * Global HTMLElementTagNameMap declarations for DUI components.
 * Provides type-safe `document.querySelector("dui-button")` etc.
 *
 * These declarations are automatically available when consuming
 * @deepfuture/dui-components via TypeScript.
 */

import type { DuiAccordion } from "./accordion/accordion.ts";
import type { DuiAccordionItem } from "./accordion/accordion-item.ts";
import type { DuiAlertDialog } from "./alert-dialog/alert-dialog.ts";
import type { DuiAlertDialogTrigger } from "./alert-dialog/alert-dialog-trigger.ts";
import type { DuiAlertDialogPopup } from "./alert-dialog/alert-dialog-popup.ts";
import type { DuiAlertDialogClose } from "./alert-dialog/alert-dialog-close.ts";
import type { DuiAvatar } from "./avatar/avatar.ts";
import type { DuiBadge } from "./badge/badge.ts";
import type { DuiBreadcrumb } from "./breadcrumb/breadcrumb.ts";
import type { DuiBreadcrumbItem } from "./breadcrumb/breadcrumb-item.ts";
import type { DuiBreadcrumbLink } from "./breadcrumb/breadcrumb-link.ts";
import type { DuiBreadcrumbPage } from "./breadcrumb/breadcrumb-page.ts";
import type { DuiBreadcrumbSeparator } from "./breadcrumb/breadcrumb-separator.ts";
import type { DuiBreadcrumbEllipsis } from "./breadcrumb/breadcrumb-ellipsis.ts";
import type { DuiButton } from "./button/button.ts";
import type { DuiCalendar } from "./calendar/calendar.ts";
import type { DuiCheckbox } from "./checkbox/checkbox.ts";
import type { DuiCheckboxGroup } from "./checkbox/checkbox-group.ts";
import type { DuiCollapsible } from "./collapsible/collapsible.ts";
import type { DuiCombobox } from "./combobox/combobox.ts";
import type { DuiCommand } from "./command/command.ts";
import type { DuiCommandInput } from "./command/command-input.ts";
import type { DuiCommandList } from "./command/command-list.ts";
import type { DuiCommandGroup } from "./command/command-group.ts";
import type { DuiCommandItem } from "./command/command-item.ts";
import type { DuiCommandEmpty } from "./command/command-empty.ts";
import type { DuiCommandSeparator } from "./command/command-separator.ts";
import type { DuiCommandShortcut } from "./command/command-shortcut.ts";
import type { DuiDataTable } from "./data-table/data-table.ts";
import type { DuiDialog } from "./dialog/dialog.ts";
import type { DuiDialogTrigger } from "./dialog/dialog-trigger.ts";
import type { DuiDialogPopup } from "./dialog/dialog-popup.ts";
import type { DuiDialogClose } from "./dialog/dialog-close.ts";
import type { DuiDropzone } from "./dropzone/dropzone.ts";
import type { DuiIcon } from "./icon/icon.ts";
import type { DuiInput } from "./input/input.ts";
import type { DuiMenu } from "./menu/menu.ts";
import type { DuiMenuItem } from "./menu/menu-item.ts";
import type { DuiMenubar } from "./menubar/menubar.ts";
import type { DuiNumberField } from "./number-field/number-field.ts";
import type { DuiPopover } from "./popover/popover.ts";
import type { DuiPopoverTrigger } from "./popover/popover-trigger.ts";
import type { DuiPopoverPopup } from "./popover/popover-popup.ts";
import type { DuiPopoverClose } from "./popover/popover-close.ts";
import type { DuiPortal } from "./portal/portal.ts";
import type { DuiPreviewCard } from "./preview-card/preview-card.ts";
import type { DuiPreviewCardTrigger } from "./preview-card/preview-card-trigger.ts";
import type { DuiPreviewCardPopup } from "./preview-card/preview-card-popup.ts";
import type { DuiProgress } from "./progress/progress.ts";
import type { DuiRadio } from "./radio/radio.ts";
import type { DuiRadioGroup } from "./radio/radio-group.ts";
import type { DuiScrollArea } from "./scroll-area/scroll-area.ts";
import type { DuiSelect } from "./select/select.ts";
import type { DuiSeparator } from "./separator/separator.ts";
import type { DuiSidebarProvider } from "./sidebar/sidebar-provider.ts";
import type { DuiSidebar } from "./sidebar/sidebar.ts";
import type { DuiSidebarTrigger } from "./sidebar/sidebar-trigger.ts";
import type { DuiSidebarContent } from "./sidebar/sidebar-content.ts";
import type { DuiSidebarHeader } from "./sidebar/sidebar-header.ts";
import type { DuiSidebarFooter } from "./sidebar/sidebar-footer.ts";
import type { DuiSidebarGroup } from "./sidebar/sidebar-group.ts";
import type { DuiSidebarGroupLabel } from "./sidebar/sidebar-group-label.ts";
import type { DuiSidebarMenu } from "./sidebar/sidebar-menu.ts";
import type { DuiSidebarMenuItem } from "./sidebar/sidebar-menu-item.ts";
import type { DuiSidebarMenuButton } from "./sidebar/sidebar-menu-button.ts";
import type { DuiSidebarSeparator } from "./sidebar/sidebar-separator.ts";
import type { DuiSidebarInset } from "./sidebar/sidebar-inset.ts";
import type { DuiSlider } from "./slider/slider.ts";
import type { DuiSpinner } from "./spinner/spinner.ts";
import type { DuiSwitch } from "./switch/switch.ts";
import type { DuiTabs } from "./tabs/tabs.ts";
import type { DuiTabsList } from "./tabs/tabs-list.ts";
import type { DuiTab } from "./tabs/tab.ts";
import type { DuiTabsPanel } from "./tabs/tabs-panel.ts";
import type { DuiTabsIndicator } from "./tabs/tabs-indicator.ts";
import type { DuiTextarea } from "./textarea/textarea.ts";
import type { DuiToggle } from "./toggle/toggle.ts";
import type { DuiToggleGroup } from "./toggle/toggle-group.ts";
import type { DuiToolbar } from "./toolbar/toolbar.ts";
import type { DuiTooltip } from "./tooltip/tooltip.ts";
import type { DuiTooltipTrigger } from "./tooltip/tooltip-trigger.ts";
import type { DuiTooltipPopup } from "./tooltip/tooltip-popup.ts";
import type { DuiTrunc } from "./trunc/trunc.ts";

declare global {
  interface HTMLElementTagNameMap {
    "dui-accordion": DuiAccordion;
    "dui-accordion-item": DuiAccordionItem;
    "dui-alert-dialog": DuiAlertDialog;
    "dui-alert-dialog-trigger": DuiAlertDialogTrigger;
    "dui-alert-dialog-popup": DuiAlertDialogPopup;
    "dui-alert-dialog-close": DuiAlertDialogClose;
    "dui-avatar": DuiAvatar;
    "dui-badge": DuiBadge;
    "dui-breadcrumb": DuiBreadcrumb;
    "dui-breadcrumb-item": DuiBreadcrumbItem;
    "dui-breadcrumb-link": DuiBreadcrumbLink;
    "dui-breadcrumb-page": DuiBreadcrumbPage;
    "dui-breadcrumb-separator": DuiBreadcrumbSeparator;
    "dui-breadcrumb-ellipsis": DuiBreadcrumbEllipsis;
    "dui-button": DuiButton;
    "dui-calendar": DuiCalendar;
    "dui-checkbox": DuiCheckbox;
    "dui-checkbox-group": DuiCheckboxGroup;
    "dui-collapsible": DuiCollapsible;
    "dui-combobox": DuiCombobox;
    "dui-command": DuiCommand;
    "dui-command-input": DuiCommandInput;
    "dui-command-list": DuiCommandList;
    "dui-command-group": DuiCommandGroup;
    "dui-command-item": DuiCommandItem;
    "dui-command-empty": DuiCommandEmpty;
    "dui-command-separator": DuiCommandSeparator;
    "dui-command-shortcut": DuiCommandShortcut;
    "dui-data-table": DuiDataTable;
    "dui-dialog": DuiDialog;
    "dui-dialog-trigger": DuiDialogTrigger;
    "dui-dialog-popup": DuiDialogPopup;
    "dui-dialog-close": DuiDialogClose;
    "dui-dropzone": DuiDropzone;
    "dui-icon": DuiIcon;
    "dui-input": DuiInput;
    "dui-menu": DuiMenu;
    "dui-menu-item": DuiMenuItem;
    "dui-menubar": DuiMenubar;
    "dui-number-field": DuiNumberField;
    "dui-popover": DuiPopover;
    "dui-popover-trigger": DuiPopoverTrigger;
    "dui-popover-popup": DuiPopoverPopup;
    "dui-popover-close": DuiPopoverClose;
    "dui-portal": DuiPortal;
    "dui-preview-card": DuiPreviewCard;
    "dui-preview-card-trigger": DuiPreviewCardTrigger;
    "dui-preview-card-popup": DuiPreviewCardPopup;
    "dui-progress": DuiProgress;
    "dui-radio": DuiRadio;
    "dui-radio-group": DuiRadioGroup;
    "dui-scroll-area": DuiScrollArea;
    "dui-select": DuiSelect;
    "dui-separator": DuiSeparator;
    "dui-sidebar-provider": DuiSidebarProvider;
    "dui-sidebar": DuiSidebar;
    "dui-sidebar-trigger": DuiSidebarTrigger;
    "dui-sidebar-content": DuiSidebarContent;
    "dui-sidebar-header": DuiSidebarHeader;
    "dui-sidebar-footer": DuiSidebarFooter;
    "dui-sidebar-group": DuiSidebarGroup;
    "dui-sidebar-group-label": DuiSidebarGroupLabel;
    "dui-sidebar-menu": DuiSidebarMenu;
    "dui-sidebar-menu-item": DuiSidebarMenuItem;
    "dui-sidebar-menu-button": DuiSidebarMenuButton;
    "dui-sidebar-separator": DuiSidebarSeparator;
    "dui-sidebar-inset": DuiSidebarInset;
    "dui-slider": DuiSlider;
    "dui-spinner": DuiSpinner;
    "dui-switch": DuiSwitch;
    "dui-tabs": DuiTabs;
    "dui-tabs-list": DuiTabsList;
    "dui-tab": DuiTab;
    "dui-tabs-panel": DuiTabsPanel;
    "dui-tabs-indicator": DuiTabsIndicator;
    "dui-textarea": DuiTextarea;
    "dui-toggle": DuiToggle;
    "dui-toggle-group": DuiToggleGroup;
    "dui-toolbar": DuiToolbar;
    "dui-tooltip": DuiTooltip;
    "dui-tooltip-trigger": DuiTooltipTrigger;
    "dui-tooltip-popup": DuiTooltipPopup;
    "dui-trunc": DuiTrunc;
  }
}
