/**
 * DESIGN.md template generator.
 *
 * Takes a resolved config (colors as hex, fonts, radii) and produces
 * a spec-compliant DESIGN.md string with YAML front matter and
 * markdown prose sections.
 */

export interface DesignMdConfig {
  /** Hex colors for YAML front matter */
  colors: {
    background: string;
    foreground: string;
    accent: string;
    destructive: string;
    // Derived
    "surface-1": string;
    "surface-2": string;
    "surface-3": string;
    "text-1": string;
    "text-2": string;
    "text-3": string;
    border: string;
    "accent-subtle": string;
    "destructive-subtle": string;
  };
  /** Original OKLCH strings for documentation */
  oklchOriginals: {
    background: string;
    foreground: string;
    accent: string;
    destructive: string;
  };
  fonts: {
    sans: string;
    serif: string;
    mono: string;
  };
  /** Base radius value (e.g. "0.5rem") */
  radiusBase: string;
  /** Whether to include extended interaction grammar sections */
  includeGrammar: boolean;
  /** Custom grammar section overrides (heading → markdown body) */
  grammarOverrides?: Record<string, string>;
}

/** Generate the complete DESIGN.md string. */
export function generateDesignMd(config: DesignMdConfig): string {
  const parts: string[] = [];

  parts.push(generateFrontMatter(config));
  parts.push(""); // blank line after front matter
  parts.push(generateVisualSections(config));

  if (config.includeGrammar) {
    parts.push(""); // blank line before grammar
    parts.push(generateGrammarSections(config.grammarOverrides));
  }

  return parts.join("\n");
}

/* ═══════════════════════════════════════════════════════════════════
 * YAML Front Matter
 * ═══════════════════════════════════════════════════════════════════ */

function generateFrontMatter(config: DesignMdConfig): string {
  const c = config.colors;
  const f = config.fonts;

  // Compute radius scale from base
  const baseRem = parseFloat(config.radiusBase) || 0.5;

  const yaml = `---
# DESIGN.md — Generated by DUI
# Spec: https://github.com/nicholasgasior/design.md (alpha)
#
# OKLCH originals (for tools with native OKLCH support):
#   background:  ${config.oklchOriginals.background}
#   foreground:  ${config.oklchOriginals.foreground}
#   accent:      ${config.oklchOriginals.accent}
#   destructive: ${config.oklchOriginals.destructive}
#
# Note: The names below are spec-format identifiers for tooling
# (e.g. import-design-md.ts). For DUI CSS custom property names
# (--space-*, --text-*, --radius-*), see the prose sections below.

colors:
  background: "${c.background}"
  foreground: "${c.foreground}"
  accent: "${c.accent}"
  destructive: "${c.destructive}"
  surface-1: "${c["surface-1"]}"
  surface-2: "${c["surface-2"]}"
  surface-3: "${c["surface-3"]}"
  text-1: "${c["text-1"]}"
  text-2: "${c["text-2"]}"
  text-3: "${c["text-3"]}"
  border: "${c.border}"
  accent-subtle: "${c["accent-subtle"]}"
  destructive-subtle: "${c["destructive-subtle"]}"

typography:
  headline-lg:
    fontFamily: ${f.sans}
    fontSize: 36px
    fontWeight: 600
    lineHeight: 1.11
    letterSpacing: -0.02em
  headline-md:
    fontFamily: ${f.sans}
    fontSize: 30px
    fontWeight: 600
    lineHeight: 1.2
    letterSpacing: -0.015em
  headline-sm:
    fontFamily: ${f.sans}
    fontSize: 24px
    fontWeight: 600
    lineHeight: 1.33
    letterSpacing: -0.01em
  body-lg:
    fontFamily: ${f.sans}
    fontSize: 18px
    fontWeight: 400
    lineHeight: 1.56
  body-md:
    fontFamily: ${f.sans}
    fontSize: 16px
    fontWeight: 400
    lineHeight: 1.5
  body-sm:
    fontFamily: ${f.sans}
    fontSize: 14px
    fontWeight: 400
    lineHeight: 1.43
  label-lg:
    fontFamily: ${f.sans}
    fontSize: 14px
    fontWeight: 500
    lineHeight: 1.43
  label-md:
    fontFamily: ${f.sans}
    fontSize: 12px
    fontWeight: 500
    lineHeight: 1.33
  label-sm:
    fontFamily: ${f.sans}
    fontSize: 10px
    fontWeight: 500
    lineHeight: 1.2
  code:
    fontFamily: ${f.mono}
    fontSize: 14px
    fontWeight: 400
    lineHeight: 1.5

rounded:
  none: 0px
  xs: ${pxFrom(Math.max(baseRem - 0.375, 0))}
  sm: ${pxFrom(Math.max(baseRem - 0.25, 0))}
  md: ${pxFrom(baseRem)}
  lg: ${pxFrom(baseRem + 0.5)}
  xl: ${pxFrom(baseRem + 1)}
  2xl: ${pxFrom(baseRem + 1.5)}
  full: 9999px
---`;

  return yaml;
}

function pxFrom(rem: number): string {
  return `${Math.round(rem * 16)}px`;
}

/* ═══════════════════════════════════════════════════════════════════
 * Visual Identity Sections (8 standard)
 * ═══════════════════════════════════════════════════════════════════ */

function generateVisualSections(config: DesignMdConfig): string {
  const o = config.oklchOriginals;
  const f = config.fonts;

  return `
## Overview

This design system is built on DUI, a Lit-based web component library with two-layer inheritance. Unstyled primitives provide structure and behavior; styled components extend them with aesthetic CSS and design tokens.

The visual identity is minimal, professional, and density-aware. It uses a neutral canvas with a single accent color for interactive elements, clear typographic hierarchy via text-box trimming, and consistent spacing through a base-4 scale.

## Colors

DUI's color system is built on 4 OKLCH primitives. Everything else is derived at runtime via \`oklch(from …)\` and \`color-mix()\`.

### Primitives

| Token | OKLCH | Role |
|---|---|---|
| \`--background\` | \`${o.background}\` | Page/app background |
| \`--foreground\` | \`${o.foreground}\` | Primary text color |
| \`--accent\` | \`${o.accent}\` | Brand/interactive color |
| \`--destructive\` | \`${o.destructive}\` | Danger/error color |

### Derived tokens

Surfaces shift \`--background\` lightness: \`--surface-1\` (+0.02), \`--surface-2\` (+0.05), \`--surface-3\` (+0.09).

Text tiers reduce \`--foreground\` alpha: \`--text-1\` (0.90), \`--text-2\` (0.63), \`--text-3\` (0.45).

Borders reduce \`--foreground\` alpha: \`--border\` (0.15), \`--border-strong\` (0.25).

Accent/destructive subtle tokens apply 10% alpha over the background for tinted surfaces.

### Dark mode

Apply \`data-theme="dark"\` on \`<html>\`. The token stylesheet redefines the 4 primitives; all derived tokens update automatically. No manual dark-mode color logic needed.

## Typography

Font stack: **${f.sans}** (sans-serif), **${f.mono}** (monospace).

DUI applies \`text-box: trim-both cap alphabetic\` globally to semantic prose elements (\`h1\`–\`h6\`, \`p\`, \`li\`, \`label\`, \`td\`, \`blockquote\`). This trims invisible leading/trailing space from text boxes so glyphs sit on exact pixel boundaries. Combined with a global margin reset, **text elements have zero implicit spacing** — all vertical rhythm must be explicit via \`gap\` or \`margin\` using \`--space-*\` tokens.

**Important:** Generic containers like \`<span>\` and \`<div>\` are NOT covered by the global rule. When using a \`<span>\`, \`<div>\`, or any non-semantic element to display text, you must apply \`text-box: trim-both cap alphabetic\` yourself — otherwise the element will have excess line-height padding and spacing will look inconsistent with the rest of the system.

### Type scale

| Level | Size | Weight | Line height | Token |
|---|---|---|---|---|
| Headline LG | 36px | 600 | 1.11 | \`--text-4xl\` |
| Headline MD | 30px | 600 | 1.2 | \`--text-3xl\` |
| Headline SM | 24px | 600 | 1.33 | \`--text-2xl\` |
| Body LG | 18px | 400 | 1.56 | \`--text-lg\` |
| Body MD | 16px | 400 | 1.5 | \`--text-base\` |
| Body SM | 14px | 400 | 1.43 | \`--text-sm\` |
| Label LG | 14px | 500 | 1.43 | \`--text-sm\` |
| Label MD | 12px | 500 | 1.33 | \`--text-xs\` |
| Label SM | 10px | 500 | 1.2 | \`--text-2xs\` |

For long-form content (rendered markdown, CMS), use \`class="dui-prose"\` on the container to restore automatic heading margins, paragraph spacing, and list indentation.

## Layout

DUI uses standard CSS flexbox and grid for all layout — no layout wrapper components. Spacing uses a base-4 token scale (\`--space-1\` = 4px through \`--space-96\` = 384px).

Key spacing guidelines:

| Relationship | Spacing |
|---|---|
| Title → subtitle | \`--space-1\` to \`--space-2\` |
| Heading → body content | \`--space-3\` to \`--space-4\` |
| Between sections | \`--space-5\` to \`--space-6\` |
| Label → value (cards) | \`--space-2\` to \`--space-3\` |
| List/stack items | \`--space-2\` to \`--space-4\` |

Because DUI trims line-height padding from text elements (\`text-box: trim-both cap alphabetic\`), the gap value IS the entire visible space between glyph edges — there is no built-in buffer. **Prefer the middle or upper end of each range.** Reserve the low end for elements with large size contrast (e.g., a large heading next to a small label) where the glyph proportions already create visual separation.

Wrap related text in a flex column with \`gap\` for vertical rhythm. Never rely on default browser margins.

## Elevation & Depth

DUI uses a surface depth model with lightness offsets from \`--background\`:

| Surface | Offset | Use |
|---|---|---|
| \`--sunken-2\` | −0.03 L | Recessed areas, code blocks |
| \`--sunken-1\` | −0.01 L | Subtle depressions |
| \`--background\` | base | Page canvas |
| \`--surface-1\` | +0.02 L | Cards, panels |
| \`--surface-2\` | +0.05 L | Elevated cards, hover states |
| \`--surface-3\` | +0.09 L | Highest elevation, popovers |

Shadow scale: \`--shadow-xs\` through \`--shadow-2xl\`. Use shadows sparingly — the lightness-based elevation model provides depth without shadows in most cases.

Z-index scale: \`--z-base\` (0) → \`--z-dropdown\` (700) → \`--z-overlay\` (900) → \`--z-modal\` (1000) → \`--z-popover\` (1100) → \`--z-toast\` (1200) → \`--z-tooltip\` (1300).

## Shapes

Radius scale based on a configurable base value:

| Token | Value | Use |
|---|---|---|
| \`--radius-none\` | 0 | Sharp corners |
| \`--radius-xs\` | 2px | Tiny elements |
| \`--radius-sm\` | 4px | Inputs, small buttons |
| \`--radius-md\` | 8px | Cards, dialogs |
| \`--radius-lg\` | 16px | Large panels |
| \`--radius-xl\` | 24px | Feature cards |
| \`--radius-full\` | 9999px | Pills, avatars |

Consistent radius usage: all elements at the same hierarchy level use the same radius token.
`;
}

/* ═══════════════════════════════════════════════════════════════════
 * Interaction Design Grammar Sections (14 extended)
 * ═══════════════════════════════════════════════════════════════════ */

const DEFAULT_GRAMMAR_SECTIONS: Record<string, string> = {
  "Page Archetypes": `Define 5–8 canonical page shapes. Every screen is an instance of one — never a snowflake.

| Archetype | Structure | When to use |
|---|---|---|
| **List** | Filter bar + data table or card grid | Collections of objects |
| **Detail** | Header + tabbed or scrolling sections | Single object view |
| **Settings** | Sidebar nav + form sections | Configuration |
| **Dashboard** | Metric cards + charts + recent activity | Overview/monitoring |
| **Modal flow** | Multi-step dialog | Focused task (create, edit) |
| **Auth** | Centered card, minimal chrome | Login, signup, reset |
| **Onboarding** | Stepper + focused content | First-run experience |
| **Empty** | Illustration + single CTA | Zero-state for any archetype |

**Filter location:** Above the data table in the toolbar. Never a side panel.
**Detail layout:** Tabbed sections for objects with 3+ distinct content areas. Single scroll for simpler objects.
**App shell:** Left-rail sidebar (\`dui-sidebar-provider\`) for object-heavy products. Top-nav for flow-driven products.`,

  "Interaction Model": `**Save semantics:** Pick ONE — optimistic, explicit-save, or autosave-with-debounce. Mixing across screens makes the app feel unfinished.

**Undo strategy:** Toast-with-undo for low-stakes mutations. \`dui-alert-dialog\` confirmation only for destructive + irreversible actions. Never confirm reversible actions — it trains users to dismiss without reading.

**Selection model:** Checkbox in the first column. Shift-click for range, Cmd/Ctrl-click for multi. Selection enables bulk actions in the toolbar.

**Keyboard map:**

| Shortcut | Action |
|---|---|
| \`Cmd+K\` | Command palette (\`dui-command\`) |
| \`Cmd+S\` | Save (if explicit-save mode) |
| \`Cmd+Enter\` | Submit form / confirm dialog |
| \`Escape\` | Close overlay / cancel |`,

  "Forms & Validation": `**Validation timing:** Validate on blur for individual fields. Show summary on submit for complex forms. Real-time validation only for format-constrained fields (email, URL).

**Multi-step flows:** Use \`dui-stepper\` for flows with 3+ steps. Each step validates before advancing. Back button preserves entered data.

**Dirty state:** Warn on navigation away from unsaved changes. Use \`beforeunload\` for browser navigation and in-app route guards for SPA navigation.

**Required/optional marking:** Mark optional fields with "(optional)" text. Required is the default — don't clutter with asterisks.

**Field dependencies:** Disable dependent fields until their prerequisite is filled. Show a brief hint explaining the dependency.

Use \`dui-field\` to wrap inputs with label, description, and error message. Use \`dui-fieldset\` to group related fields.`,

  "Notification & Feedback": `**Three channels only:**

| Channel | Component | Use |
|---|---|---|
| **Toast** | Custom (future \`dui-toast\`) | Transient success/info, bottom-right, 4–6s, max 3 stacked |
| **Banner** | Inline \`div\` with tokens | Persistent page-level alerts, above content |
| **Inline** | \`dui-field\` error state | Form-bound validation messages |

**Mutation feedback:** Optimistic by default. Show \`dui-spinner\` only for operations exceeding 300ms. Full-page loader is a last resort.

**Error severity ladder:** Validation → inline (\`dui-field\`). Operation failure → toast. Page-state failure → banner. App outage → full page. Match severity to channel; never escalate.`,

  "State Patterns": `**Loading:** Use skeleton placeholders for known-shape content, \`dui-spinner\` for unknown-shape. Under 200ms, show nothing — stutter is worse than wait.

**Empty states:** Text + single CTA (\`dui-button\`) for routine empties. Illustration only for first-run zero states.

**Error hierarchy:**
- Field error → \`dui-field\` inline error
- Section failure → error message within the section, rest of page intact
- Page failure → full error state, but preserve the app shell (\`dui-sidebar-provider\`)
- App outage → full page error

**Partial failure:** Render what loaded. Mark failed sections explicitly. Never show a whole-page error for one failed widget.

**Permission states:** Use disabled controls + tooltip explaining why. Never hide UI that the user knows should exist.`,

  "Content Conventions": `**Case:** Sentence case everywhere — buttons, headings, menu items, tab labels. Never title case.

**Button voice:** Imperative verb + object: "Save changes", "Delete project", "Create workspace". Bare "Save" only in unambiguous contexts. Never "OK" or "Submit".

**Error voice:** What happened, then what to do. "Couldn't save. Check your connection and try again." Never blame the user.

**Numbers & dates:** Relative time under 7 days ("3 hours ago"), absolute beyond ("Mar 14, 2026"). ISO-ish dates in dense tables. One formatter, applied globally.

**Concept naming:** One term per domain object and freeze it (Workspace OR Team, not both). Inconsistent naming destroys product feel faster than any visual flaw.`,

  "Information Architecture": `**Primary nav:** Holds top-level objects users touch hourly. Anything weekly belongs one level deeper. Use \`dui-sidebar-provider\` with \`dui-sidebar-menu-button\` for nav items.

**Settings:** One destination, one entry point — avatar menu item OR sidebar item, never both.

**Filter & sort:** Filters live in the data table's toolbar, with the data they filter. Never a side panel.

**Command palette:** \`dui-command\` for navigation + actions. If settings appear in the palette, the settings IA is broken.

**Search:** Global OR scoped, never contextual mystery. The user knows at all times what's being searched.

**URL strategy:** Hash or path routing. Every distinct view has a URL. Back button works. Deep links work.`,

  "Density & Rhythm": `**Default density:** Pick one density level. Multi-density is a feature, not a default.

**Section rhythm:** Inter-section gap = \`--space-6\` to \`--space-8\`. Intra-section gap = \`--space-3\` to \`--space-4\`. Between page regions = \`--space-10\` or more.

**Form rhythm:** Label-to-input gap (\`--space-1\` to \`--space-2\`) = half the input-to-input gap (\`--space-3\` to \`--space-4\`).

**Table density:** Row height = 1.5× body line-height for comfortable, 1.2× for compact. Use \`dui-data-table\` with the density that matches the data volume.

**Card vs. styled div:** Use \`dui-card\` only when content has structured regions (title/description header, action slot, footer with buttons). For simple raised containers — stat tiles, metric blocks, info boxes — use a plain \`<div>\` styled with \`background: var(--surface-1); border: 1px solid var(--border); border-radius: var(--radius-lg); padding: var(--space-4)\`. Cards add header/footer layout machinery; don't pay for structure you aren't using.`,

  "Transitions & Motion": `DUI components have built-in transitions using semantic duration tokens. Reference these tokens — never specify millisecond values directly.

| Token | Duration | Use |
|---|---|---|
| \`--duration-instant\` | 50ms | Micro-interactions (checkbox tick) |
| \`--duration-fast\` | 150ms | Hover states, button press, tooltip |
| \`--duration-normal\` | 250ms | Accordion open/close, dialog enter/exit, tab switch |
| \`--duration-slow\` | 400ms | Page transitions, complex animations |

**DUI-owned transitions** (don't override): hover states, accordion open/close, dialog enter/exit, collapsible expand/collapse, popover show/hide.

**Consumer-owned transitions:** Page transitions, skeleton-to-content handoff, custom choreography, list item enter/exit.

**Easing:** Use \`--ease-out-3\` for enters (decelerating), \`--ease-in-2\` for exits (accelerating), \`--ease-in-out-3\` for moves.

**Reduced motion:** Every animation must have a \`prefers-reduced-motion: reduce\` fallback. Test the whole app with reduced motion, not just individual components.`,

  "Data Patterns": `**Pagination:** Use \`dui-data-table\`'s built-in pagination for datasets over 50 rows. Infinite scroll only for feeds/timelines. "Load more" button for mixed contexts.

**Sort:** Single-column sort by default. Column header click cycles asc → desc → none. \`dui-data-table\` handles this internally.

**Refresh:** Pull-to-refresh for mobile; explicit refresh button or polling interval for desktop. Never auto-refresh while the user is mid-action.

**Bulk operations:** Checkbox selection → toolbar actions. Show count of selected items. "Select all" selects current page; "Select all N items" for cross-page.

**Export:** Download button in the toolbar. Formats: CSV for data, PDF for reports. Show \`dui-progress\` for large exports.`,

  "Responsive Behavior": `**Breakpoints:** Use CSS container queries (\`container-type: inline-size\`) for component-level responsiveness. Page-level breakpoints via media queries.

| Breakpoint | Target |
|---|---|
| < 640px | Mobile |
| 640–1024px | Tablet |
| > 1024px | Desktop |

**Collapse rules:** Sidebar collapses to icons on tablet, hidden on mobile (toggle via hamburger). Multi-column layouts reflow to single column. Horizontal tabs → dropdown or scrollable.

**Touch targets:** Minimum 44×44px on mobile. \`dui-button\` and interactive components already meet this at default size.

**Mobile patterns:** Use dialog as bottom sheet for mobile overlays. Pull-to-refresh for feed views. Swipe-to-dismiss for toasts.`,

  "Overlay Hierarchy": `DUI has fixed overlay behaviors that are intentional safety constraints:

| Use case | Component | Behavior |
|---|---|---|
| Focused task requiring input | \`dui-dialog\` | Closes on backdrop click |
| Destructive confirmation | \`dui-alert-dialog\` | Does NOT close on backdrop click (requires explicit action) |
| Small contextual content | \`dui-popover\` | Closes on outside click |
| Brief hint on hover | \`dui-tooltip\` | Shows/hides on hover |
| Action menu | \`dui-menu\` | Closes on item select or outside click |
| Search/command palette | \`dui-command\` | Closes on selection or Escape |

**One popup at a time:** DUI's popup coordinator enforces this — opening a popover/menu/tooltip closes any other open popup. Design flows accordingly.

**Nesting:** Never nest dialogs. If a dialog needs a sub-task, use inline expansion within the dialog or a multi-step flow.

**Scroll lock:** Dialogs and alert-dialogs lock background scroll. Popovers and tooltips do not.

**Focus trap:** Dialogs and alert-dialogs trap focus. Tab cycling stays within the overlay.`,

  "Accessibility": `**Landmark structure:** Every page has \`banner\` (header), \`navigation\` (sidebar), \`main\` (content), \`contentinfo\` (footer). DUI components handle internal ARIA; pages need the structural roof.

**Route-change focus:** Move focus to the main heading on SPA navigation. Browser-default focus loss is the most common SPA accessibility bug.

**Live regions:** One \`aria-live="polite"\` region for status updates, one \`aria-live="assertive"\` for errors, both owned by the app shell. Components don't create their own.

**Skip link:** First focusable element on every page, jumps to \`main\`. Hidden until focused.

**Reduced motion:** Every animation has a no-motion fallback. Test with \`prefers-reduced-motion: reduce\` enabled.

**Color contrast:** WCAG AA minimum (4.5:1 for text, 3:1 for large text and UI components). DUI's default palette meets this; verify when customizing colors.`,

  "Iconography": `**One icon set:** Pick Lucide, Heroicons, or Material Symbols. Use it exclusively. Mixed icon sets are the most visible inconsistency.

**Size pairings:**

| Context | Size |
|---|---|
| Inline with text | 1em |
| UI affordances (buttons, nav) | 16–20px |
| Empty states, illustrations | 32px+ |

**Icon-only buttons:** Always require a \`tooltip\` (\`dui-tooltip\`) and an \`aria-label\`. No exceptions for "obvious" icons.

**Color inheritance:** All icons use \`currentColor\`. Pass SVG into \`dui-icon\`'s default slot. Override with \`--icon-color\` and \`--icon-size\` custom properties.

**Weight discipline:** Stroke OR filled within a single surface. Never mix weights on the same screen.`,
};

function generateGrammarSections(overrides?: Record<string, string>): string {
  const sections = { ...DEFAULT_GRAMMAR_SECTIONS };
  if (overrides) {
    for (const [key, value] of Object.entries(overrides)) {
      sections[key] = value;
    }
  }

  return Object.entries(sections)
    .map(([heading, body]) => `## ${heading}\n\n${body}`)
    .join("\n\n");
}
